-- Gerado de: colaboradores_rh.xls (142 funcionários)
-- Rode após sql/002_dim_rh.sql
insert into dim_rh (id_rh, nome, setor, cargo, ativo) values
('RH-0001', 'Acenir Marcos Sanches Silva', 'Manutenção Geral', 'Chefe Serviço/Seção', true),
('RH-0002', 'Adao Geraldo Goncalves Junior', 'Plantio', 'Auxiliar Plantio', true),
('RH-0003', 'Adelso Joaquim Santana', 'Autoclave (Industria)', 'Auxiliar de tratamento', true),
('RH-0004', 'Ademir Aparecido Bombonato', 'Oficina', 'Mecânico', true),
('RH-0005', 'Adriano Cardoso Santuni', 'Retiro Corrego do Campo', 'Vaqueiro', true),
('RH-0006', 'Alana Nunes Leite Catulio', 'Seg. Medicina Trabalho', 'Enfermeiro(a) do Trabalho', true),
('RH-0007', 'Alaor Abinel Anunciacao', 'HIdráulica', 'Líder', true),
('RH-0008', 'Alessandro da Silva', 'Viveiro Florestal', 'Aux Prod Viveiro Mudas I(Aplic', true),
('RH-0009', 'Alex dos Santos Cruz Honorio', 'HIdráulica', 'Aux. Man. Hidraulica', true),
('RH-0010', 'Alex Menegon de Lima', 'Plantio', 'Auxiliar Plantio(Aplic Def Agr', true),
('RH-0011', 'Alex Oliveira Silva', 'Fabrica de Sal', 'Tratorista Salgador(Coleta Sel', true),
('RH-0012', 'Allef Menezes Soares', 'Sede / Pecuária', 'Tecnico Agropecuario', true),
('RH-0013', 'Ana Isa Almeida Vieira', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas II', true),
('RH-0014', 'Anderson da Silva Correia', 'Máquinas / Tratores', 'Tratorista(Aplic def Agric)', true),
('RH-0015', 'Anderson Henrique Zacarin', 'Administração', 'Gerente de Fazenda', true),
('RH-0016', 'Anderson Rodrigues de Oliveira', 'Retiro Agua Branca', 'Vaqueiro', true),
('RH-0017', 'Andre de Souza Fonseca', 'Viveiro Florestal', 'Líder Florestal', true),
('RH-0018', 'Andre Junior da Silva Santos', 'Veículos', 'Motorista', true),
('RH-0019', 'Andre Luis Brito Gomes', 'Veículos', 'Motorista', true),
('RH-0020', 'Antonio Aparecido dos Santos', 'Plantio', 'Líder', true),
('RH-0021', 'Antonio Bispo dos Santos', 'Veículos', 'Motorista', true),
('RH-0022', 'Antonio Carlos do Nascimento', 'Administração', 'Porteiro', true),
('RH-0023', 'Antonio Junior da Silva', 'Plantio', 'Auxiliar Plantio', true),
('RH-0024', 'Antony Gabriel Goncalves Santos', 'Máquinas / Tratores', 'Tratorista(Aplic def Agric)', true),
('RH-0025', 'Aparecido Bispo Pereira', 'Retiro Poço Azul', 'Vaqueiro', true),
('RH-0026', 'Aron Mussatto Ricardo', 'Plantio', 'Auxiliar Plantio', true),
('RH-0027', 'Bruno Garcia Nascimento', 'Sede / Pecuária', 'Supervisor de Rastreabilidade', true),
('RH-0028', 'Carla Lorrany Rodrigues da Silva', 'Administração', 'Auxiliar Administrativo', true),
('RH-0029', 'Carlos Eduardo Souza de Oliveira', 'Plantio', 'Auxiliar Plantio', true),
('RH-0030', 'Caua Chagas de Souza', 'Seg. Medicina Trabalho', 'Técnico em Segurança no Trabal', true),
('RH-0031', 'Celso Chamorro', 'Corte de Eucalipto', 'Líder Corte Eucalipto', true),
('RH-0032', 'Claudenor de Souza Almeida', 'Manutenção Geral', 'Eletricista', true),
('RH-0033', 'Claudio Chamorro', 'Corte de Eucalipto', 'Operador Motosserra', true),
('RH-0034', 'Daniel Aparecido de Oliveira Bispo', 'Retiro Poço Azul', 'Materneiro', true),
('RH-0035', 'Daniel Pereira dos Santos', 'Plantio', 'Auxiliar Plantio', true),
('RH-0036', 'Dayton Cristiano Pinheiro Ferreira', 'Veículos', 'Motorista I', true),
('RH-0037', 'Dayver Felipe Honorio Araujo', 'Máquinas / Tratores', 'Tratorista(Aplic def Agric)', true),
('RH-0038', 'Derivaldo de Oliveira Flores', 'Fabrica de Sal', 'Encarregado Fabrica de Sal', true),
('RH-0039', 'Djalme Rodrigues Leocadio', 'Almoxarifado', 'Auxiliar de Almoxarifado', true),
('RH-0040', 'Douglas Pires da Silva', 'Máquinas / Tratores', 'Operador de Motoniveladora', true),
('RH-0041', 'Edilson Dias', 'Manutenção Geral', 'Caseiro', true),
('RH-0042', 'Edivaldo Soares dos Reis', 'Plantio', 'Auxiliar Plantio', true),
('RH-0043', 'Ednilson Alexandre', 'Plantio', 'Auxiliar Plantio', true),
('RH-0044', 'Edson de Jesus Pereira', 'Plantio', 'Auxiliar Plantio(Aplic Def Agr', true),
('RH-0045', 'Eduardo Catulio de Oliveira', 'Viveiro Florestal', 'Supervisor Florestal', true),
('RH-0046', 'Eduardo Fernando da Silva', 'Fabrica de Sal', 'Serviços Gerais', true),
('RH-0047', 'Eduardo Pereira Bica', 'Sede / Pecuária', 'Coordenador de Pecuária', true),
('RH-0048', 'Eduardo Ramires Franca', 'Sede / Pecuária', 'Vaqueiro', true),
('RH-0049', 'Edviges Terezinha Munhoz da Silva', 'Administração', 'Auxiliar Administrativo', true),
('RH-0050', 'Eleny Jardim', 'Administração', 'Serviços Gerais', true),
('RH-0051', 'Eli Silva Nunes Neto', 'Retiro Eucalipto', 'Vaqueiro', true),
('RH-0052', 'Elizabete Ribeiro Gonzaga', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas II', true),
('RH-0053', 'Ellen Carolina Lopo Chamorro Goncalves', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas I', true),
('RH-0054', 'Elson Clemente dos Santos', 'Plantio', 'Auxiliar Plantio', true),
('RH-0055', 'Eudimi Henrique Ribeiro da Silva', 'Retiro Barra do Cervo', 'Vaqueiro', true),
('RH-0056', 'Fabiano Nascimento Silva', 'Veículos', 'Motorista', true),
('RH-0057', 'Felipe Pereira de Menezes', 'Oficina', 'Soldador', true),
('RH-0058', 'Fernanda Floriano Picoli', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas II', true),
('RH-0059', 'Fernando Silva Nascimento', 'Plantio', 'Auxiliar Plantio', true),
('RH-0060', 'Frederico dos Santos e Souza Bonfim', 'Administração', 'Encarregado Administrativo', true),
('RH-0061', 'Gabriel Jacinto', 'Retiro Corrego do Campo', 'Vaqueiro', true),
('RH-0062', 'Gilberto Rodrigues dos Santos', 'Plantio', 'Auxiliar Plantio(Aplic Def Agr', true),
('RH-0063', 'Gilda Valeria dos Santos', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas II', true),
('RH-0064', 'Gildo de Morais Souza', 'Veículos', 'Motorista I', true),
('RH-0065', 'Gilson Dias da Silva', 'Plantio', 'Auxiliar Plantio(Aplic Def Agr', true),
('RH-0066', 'Gustavo Henrique Goncalves dos Santos', 'Sede / Pecuária', 'Vaqueiro', true),
('RH-0067', 'Heleaneo Plinio da Silva', 'Sede / Pecuária', 'Vaqueiro', true),
('RH-0068', 'Helena Valerio dos Santos', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas II', true),
('RH-0069', 'Helio Mauricio Vieira Lima', 'Administração', 'Assistente de Controladoria', true),
('RH-0070', 'Israel Lima de Andrade', 'Administração', 'Assistente de Controladoria', true),
('RH-0071', 'Izaias Galdino da Luz', 'Plantio', 'Auxiliar Plantio', true),
('RH-0072', 'Jean do Nascimento Oliveira', 'Máquinas / Tratores', 'Tratorista II', true),
('RH-0073', 'Jefferson Maicon Mariano de Oliveira', 'Oficina', 'Mecânico', true),
('RH-0074', 'Joao Lucas de Souza Correia', 'Máquinas / Tratores', 'Tratorista(Aplic def Agric)', true),
('RH-0075', 'Joao Paulo da Costa Caetano', 'Plantio', 'Auxiliar Plantio', true),
('RH-0076', 'Joao Paulo da Silva', 'Máquinas / Tratores', 'Operador Pá Carregadeira(Aplic', true),
('RH-0077', 'Jose Carlos da Silva', 'Manutenção Geral', 'Caseiro', true),
('RH-0078', 'Jose Guilherme da Silva', 'Sede / Pecuária', 'Vaqueiro', true),
('RH-0079', 'Jose Maria da Luz', 'Serviços Gerais', 'Serviços Gerais', true),
('RH-0080', 'Jose Ricardo Leite Portugues', 'Veículos', 'Motorista I', true),
('RH-0081', 'Jose Roberto da Silva', 'Fabrica de Sal', 'Serviços Gerais', true),
('RH-0082', 'Jose Roberto Dias', 'Oficina', 'Coordenador Man Mecanica', true),
('RH-0083', 'Josimeire Aquino Santos Fonseca', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas II', true),
('RH-0084', 'Josivaldo do Nascimento Verissimo', 'Máquinas / Tratores', 'Tratorista I(Aplic Def Agric)', true),
('RH-0085', 'Juliano Pereira da Silva', 'Máquinas / Tratores', 'Operador de Motoniveladora', true),
('RH-0086', 'Junior Cezar de Souza Passos', 'Veículos', 'Motorista I', true),
('RH-0087', 'Junior Rodrigues de Oliveira', 'Retiro Eucalipto', 'Capataz Na Pecuária', true),
('RH-0088', 'Luan Comege da Silva', 'Retiro Taquarussu', 'Capataz na Pecuária', true),
('RH-0089', 'Luan Vinicius da Silva Ferreira', 'Sede / Pecuária', 'Capataz na Pecuária', true),
('RH-0090', 'Lucas da Silva Galdino', 'Manutenção Geral', 'Motorista Comboista', true),
('RH-0091', 'Lucas Rodrigues Hilario', 'Retiro Taquarussu', 'Vaqueiro', true),
('RH-0092', 'Luciano Alves de Lima', 'Máquinas / Tratores', 'Tratorista(Aplic def Agric)', true),
('RH-0093', 'Luiz Henrique Rodrigues da Silva', 'Máquinas / Tratores', 'Chefe Serviço/Seção', true),
('RH-0094', 'Manuel Josenildo dos Santos', 'Plantio', 'Auxiliar Plantio', true),
('RH-0095', 'Marcelo Fernandes', 'Máquinas / Tratores', 'Tratorista(Aplic def Agric)', true),
('RH-0096', 'Marcelo Lopes Siqueira', 'Plantio', 'Auxiliar Plantio', true),
('RH-0097', 'Marcio Antonio dos Santos', 'Máquinas / Tratores', 'Operador Pa Carregadeira', true),
('RH-0098', 'Marcio Junior Faria dos Santos', 'Retiro Eucalipto', 'Vaqueiro', true),
('RH-0099', 'Marcio Thiago Gonzaga Santos', 'Máquinas / Tratores', 'Tratorista', true),
('RH-0100', 'Marco Aurelio Lopes de Araujo', 'Oficina', 'Soldador', true),
('RH-0101', 'Marcos Aparecido Batista Antonaji', 'Máquinas / Tratores', 'Tratorista', true),
('RH-0102', 'Marcos Aparecido da Chagas', 'Veículos', 'Motorista', true),
('RH-0103', 'Marcos Pereira de Araújo', 'Retiro Corrego do Campo', 'Capataz na Pecuária', true),
('RH-0104', 'Marcos Vieira Silva', 'Sede / Pecuária', 'Tecnico Agropecuario', true),
('RH-0105', 'Mareval Mariano da Silva', 'HIdráulica', 'Aux. Man. Hidraulica', true),
('RH-0106', 'Matheus Alexandre da Silva', 'Sede / Pecuária', 'Vaqueiro', true),
('RH-0107', 'Matheus Santos Bica', 'Retiro Agua Branca', 'Capataz Na Pecuária', true),
('RH-0108', 'Michelle Custodio', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas II', true),
('RH-0109', 'Milton Francisco da Silva', 'Fabrica de Sal', 'Serviços Gerais', true),
('RH-0110', 'Murilo Silvestre Carvalho', 'Sede / Pecuária', 'Auxiliar de Rastreabilidade', true),
('RH-0111', 'Nilton dos Santos', 'Máquinas / Tratores', 'Tratorista', true),
('RH-0112', 'Odair Machado de Oliveira', 'Plantio', 'Auxiliar Plantio', true),
('RH-0113', 'Olavo da Silva Junior', 'Veículos', 'Motorista', true),
('RH-0114', 'Onofre Gregorio Ferreira', 'Retiro Taquarussu', 'Vaqueiro', true),
('RH-0115', 'Paulo Henrique de Oliveira', 'Administração', 'Assistente de Compras', true),
('RH-0116', 'Paulo Henrique de Souza Maia', 'Manutenção Geral', 'Líder de Pátio', true),
('RH-0117', 'Paulo Junior dos Santos', 'Viveiro Florestal', 'Aux Prod Viveiro Mudas I(Aplic', true),
('RH-0118', 'Pedro Henrique dos Santos Lima', 'Máquinas / Tratores', 'Tratorista(Aplic def Agric)', true),
('RH-0119', 'Pedro Henrique Lemes Bombonato', 'Oficina', 'Auxiliar de Mecanica', true),
('RH-0120', 'Ramon Jose Nader', 'Sede / Pecuária', 'Médico Veterinário', true),
('RH-0121', 'Reinaldo Oliveira de Almeida', 'Máquinas / Tratores', 'Tratorista(Aplic def Agric)', true),
('RH-0122', 'Rita de Cassia dos Santos Marcondes', 'Administração', 'Cozinheira Geral', true),
('RH-0123', 'Roberto Carlos Ribeiro de Souza', 'Manutenção Geral', 'Pintor', true),
('RH-0124', 'Robson Nelson Ferreira', 'Plantio', 'Líder', true),
('RH-0125', 'Rodnei da Silva Menezes', 'Plantio', 'Auxiliar Plantio', true),
('RH-0126', 'Romario Fernandes Moreira', 'Plantio', 'Auxiliar Plantio', true),
('RH-0127', 'Ronaldo Pontes Ferreira', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas I', true),
('RH-0128', 'Roselaine da Silva Batista', 'Administração', 'Cozinheira Geral', true),
('RH-0129', 'Saulo Patricio Silva Moraes', 'Administração', 'Porteiro', true),
('RH-0130', 'Savio Silva Moraes', 'Administração', 'Porteiro', true),
('RH-0131', 'Sebastiao Aparecido Grance', 'Manutenção Geral', 'Borracheiro', true),
('RH-0132', 'Sergio de Souza Nunes', 'Administração', 'Assistente de Compras', true),
('RH-0133', 'Severina Tavares de Andrade Silva', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas II', true),
('RH-0134', 'Sidnei Alves da Silva', 'Retiro Poço Azul', 'Capataz na Pecuária', true),
('RH-0135', 'Silvana Maria da Silva', 'Administração', 'Cozinheira Geral', true),
('RH-0136', 'Tania dos Santos Pereira', 'Viveiro Florestal', 'Aux. Prod. Viveiro Mudas II', true),
('RH-0137', 'Uelinton Gonçalves Araujo da Silva', 'Fabrica de Sal', 'Serviços Gerais', true),
('RH-0138', 'Vagner Aparecido dos Santos', 'Retiro Barra do Cervo', 'Capataz na Pecuária', true),
('RH-0139', 'Vagner de Freitas Silva', 'Retiro Corrego do Campo', 'Materneiro', true),
('RH-0140', 'Vanderlei Gonsalves de Oliveira', 'Corte de Eucalipto', 'Operador I', true),
('RH-0141', 'Vanderlei Martins Santana', 'Plantio', 'Auxiliar Plantio', true),
('RH-0142', 'Wesley Maycon Rodrigues dos Santos', 'Retiro Taquarussu', 'Vaqueiro', true)
on conflict (id_rh) do update set
    nome = excluded.nome,
    setor = excluded.setor,
    cargo = excluded.cargo,
    ativo = excluded.ativo;

select setor, count(*) as qtd from dim_rh where ativo group by setor order by setor;
